/// Flutter icons Afia4Icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Afia4Icons
///      fonts:
///       - asset: fonts/Afia4Icons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Afia4Icons {
  Afia4Icons._();

  static const _kFontFam = 'Afia4Icons';
  static const String? _kFontPkg = null;

  static const IconData content_cut = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_6 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_alt_slash = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_slash = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flow_cross = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alphabet_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_pair = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbed_arrow = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beam_wake = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragon_breath = IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forging = IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gloop = IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mine_wagon = IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ophiuchus = IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData overhead = IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pawprint = IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recycle = IconData(0xea7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData regeneration = IconData(0xea7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reverse = IconData(0xea80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite = IconData(0xea8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe_prints = IconData(0xea98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spawn_node = IconData(0xeaab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinning_sword = IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splash = IconData(0xeab5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supersonic_arrow = IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uncertainty = IconData(0xeadb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underhand = IconData(0xeadc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xf21c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opencart = IconData(0xf23d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_lizard_o = IconData(0xf258, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_dollar = IconData(0xf651, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_dollar = IconData(0xf653, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragon = IconData(0xf6d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biking = IconData(0xf84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
